version: "3"

services:
  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://case_management:devpassword@db/case_management
      - DJANGO_DEBUG=True
      - NODE_ENV=development
      - DJANGO_DEBUG_TOOLBAR
      - DJANGO_SECRET_KEY=not-secret-in-dev
      - DJANGO_WHITENOISE_AUTOREFRESH=True
      - TAG_MANAGER_ENABLED=False
      - APP_URL="https://app.casefile.org.za"
      - DASHBOARD_URL="https://dashboard.casefile.org.za"
      - CORS_ALLOWED_ORIGIN_REGEXES=^http://localhost:\d+$$,^http://127.0.0.1:\d+$$
    env_file:
      - development.env
  db:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=case_management
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=case_management
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  db-data:
