[[headers]]
  for = "index.html"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"
  for = "serviceworker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"