# Generated by Django 3.2.4 on 2021-06-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('meeting_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='case_management.case')),
            ],
        ),
    ]
