# Generated by Django 3.2.4 on 2021-07-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_auto_20210706_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(default='In person meeting', max_length=50),
        ),
    ]
