# Generated by Django 3.2.4 on 2021-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='clients',
            field=models.ManyToManyField(to='case_management.Client'),
        ),
    ]
