# Generated by Django 3.2.4 on 2021-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_case_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cases',
            field=models.ManyToManyField(blank=True, to='case_management.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='clients',
            field=models.ManyToManyField(blank=True, to='case_management.Client'),
        ),
    ]
