# Generated by Django 3.2.4 on 2021-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_auto_20210901_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
