# Generated by Django 3.2.4 on 2021-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_alter_user_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseoffice',
            name='case_office_code',
            field=models.CharField(default='D00', max_length=3),
        ),
    ]
