# Generated by Django 3.2.4 on 2021-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0013_legalcasefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalcase',
            name='case_types',
            field=models.ManyToManyField(blank=True, to='case_management.CaseType'),
        ),
        migrations.AlterField(
            model_name='legalcase',
            name='state',
            field=models.CharField(choices=[('Opened', 'Opened'), ('InProgress', 'In Progress'), ('Hanging', 'Hanging'), ('Pending', 'Pending'), ('Referred', 'Referred'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Closed', 'Closed')], default='Opened', max_length=10),
        ),
    ]
