# Generated by Django 3.2.4 on 2021-10-28 20:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0013_legalcasefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='official_identifier',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='official_identifier_type',
            field=models.CharField(
                choices=[
                    ('National', 'National Identity Number'),
                    ('Passport', 'Passport Number'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='client',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
