# Generated by Django 3.2.4 on 2021-10-27 21:10
# set_default_description added by rikusv

import os
from django.db import migrations, models


def set_default_description(apps, schema_editor):
    LegalCaseFile = apps.get_model('case_management', 'LegalCaseFile')

    for obj in LegalCaseFile.objects.filter(description=''):
        obj.description = os.path.basename(obj.upload.name)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0013_legalcasefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcasefile',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(set_default_description, migrations.RunPython.noop),
    ]
