# Generated by Django 3.2.4 on 2021-10-29 21:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0014_auto_20211028_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='alternative_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='alternative_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
