# Generated by Django 3.2.4 on 2021-10-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0014_auto_20211028_2057'),
        ('case_management', '0014_update_case_number_format'),
    ]

    operations = [
    ]
