# Generated by Django 3.2.4 on 2021-11-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0014_legalcasefile_description'),
        ('case_management', '0015_merge_20211029_1045'),
    ]

    operations = [
    ]
