# Generated by Django 3.2.4 on 2021-11-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0015_merge_20211029_1045'),
        ('case_management', '0016_auto_20211104_2121'),
    ]

    operations = [
    ]
