# Generated by Django 3.2.4 on 2021-11-11 19:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0016_auto_20211104_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalcase',
            name='has_respondent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='respondent_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name='legalcase',
            name='respondent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
