# Generated by Django 3.2.4 on 2021-11-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0016_merge_20211111_1634'),
        ('case_management', '0017_merge_20211108_1229'),
    ]

    operations = [
    ]
