# Generated by Django 3.2.4 on 2021-11-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0015_merge_20211029_1045'),
        ('case_management', '0017_auto_20211111_1947'),
    ]

    operations = [
    ]
