# Generated by Django 3.2.4 on 2021-11-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0018_merge_20211111_2013'),
        ('case_management', '0018_merge_20211115_0940'),
    ]

    operations = [
    ]
