# Generated by Django 3.2.4 on 2021-11-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0014_auto_20211028_1527'),
        ('case_management', '0019_merge_20211117_1445'),
    ]

    operations = [
    ]
