# Generated by Django 3.2.4 on 2021-12-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0020_merge_20211119_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='legal_case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_files', to='case_management.legalcasefile'),
        ),
    ]
