# Generated by Django 3.2.4 on 2021-11-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0020_merge_20211119_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='case_management.log')),
            ],
        ),
    ]
