# Generated by Django 3.2.4 on 2021-12-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0021_logchange'),
        ('case_management', '0021_meeting_legal_case_file'),
    ]

    operations = [
    ]
