# Generated by Django 3.2.4 on 2022-01-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0021_meeting_legal_case_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='legal_case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_case_files', to='case_management.legalcasefile'),
        ),
    ]
