# Generated by Django 3.2.4 on 2021-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0021_logchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='logchange',
            name='action',
            field=models.CharField(choices=[('Change', 'Change'), ('Add', 'Add'), ('Remove', 'Remove')], default='Change', max_length=10),
            preserve_default=False,
        ),
    ]
