# Generated by Django 3.2.4 on 2022-01-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0021_meeting_legal_case_file'),
        ('case_management', '0022_logchange_action'),
    ]

    operations = [
    ]
