# Generated by Django 3.2.4 on 2022-02-12 16:12
# link_meetings_to_case_updates added by rikusv

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


def link_meetings_to_case_updates(apps, schema_editor):
    Meeting = apps.get_model('case_management', 'Meeting')
    CaseUpdate = apps.get_model('case_management', 'CaseUpdate')
    for obj in Meeting.objects.filter(case_update=None):
        CaseUpdate.objects.create(legal_case=obj.legal_case, meeting=obj)

def move_files_to_new_table_and_link_to_case_updates(apps, schema_editor):
    LegalCaseFile = apps.get_model('case_management', 'LegalCaseFile')
    File = apps.get_model('case_management', 'File')
    CaseUpdate = apps.get_model('case_management', 'CaseUpdate')
    for obj in LegalCaseFile.objects.all():
        case_update = CaseUpdate.objects.create(legal_case=obj.legal_case)
        new_obj = File.objects.create(
            case_update=case_update,
            legal_case=obj.legal_case,
            upload=obj.upload,
            description=obj.description,
            created_at=obj.created_at,
            updated_at=obj.updated_at,
            created_by=obj.created_by,
            updated_by=obj.updated_by
        )



class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0025_alter_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_updates', to='case_management.legalcase')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='legal_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='case_management.legalcase'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('case_update', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='case_management.caseupdate')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case_management.legalcase')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('case_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='case_management.caseupdate')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('legal_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='case_management.legalcase')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='meeting',
            name='case_update',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='case_management.caseupdate'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='legal_case_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_case_files', to='case_management.file'),
        ),
        migrations.RunPython(move_files_to_new_table_and_link_to_case_updates, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='LegalCaseFile',
        ),
        migrations.RunPython(link_meetings_to_case_updates, migrations.RunPython.noop),
    ]
