# Generated by Django 3.2.4 on 2022-01-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0022_merge_0021_logchange_0021_meeting_legal_case_file'),
        ('case_management', '0025_alter_log_user'),
    ]

    operations = [
    ]
