# Generated by Django 3.2.4 on 2022-04-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0022_alter_meeting_legal_case_file'),
        ('case_management', '0025_alter_log_user'),
    ]

    operations = [
    ]
