# Generated by Django 3.2.4 on 2022-02-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0022_alter_meeting_legal_case_file'),
        ('case_management', '0026_client_users'),
    ]

    operations = [
    ]
