# Generated by Django 3.2.4 on 2022-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0026_merge_20220124_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logchange',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
