# Generated by Django 3.2.4 on 2022-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0027_merge_20220203_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_group',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Reporting', 'Reporting'), ('AdviceOfficeAdmin', 'Advice Office Admin'), ('CaseWorker', 'Case Worker')], max_length=20, null=True),
        ),
    ]
