# Generated by Django 3.2.4 on 2022-02-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0026_auto_20220212_1612'),
        ('case_management', '0027_merge_20220203_0731'),
    ]

    operations = [
    ]
