# Generated by Django 3.2.4 on 2022-02-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0028_merge_20220221_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='legal_case_file',
        ),
        migrations.AddField(
            model_name='meeting',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='case_management.file'),
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='case_management.file'),
        ),
    ]
