# Generated by Django 3.2.4 on 2022-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0029_auto_20220226_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='advice_offered',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='advice_was_offered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
