# Generated by Django 3.2.4 on 2022-04-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0028_user_permission_group'),
        ('case_management', '0030_auto_20220306_0933'),
    ]

    operations = [
    ]
