# Generated by Django 3.2.4 on 2022-02-12 16:12
# link_meetings_to_case_updates added by rikusv

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


def add_missing_updated_by(apps, schema_editor):
    '''If updated_by is missing, set same as created_by'''
    model_names = (
        'CaseUpdate',
        'CaseOffice',
        'CaseType',
        'Client',
        'File',
        'LegalCase',
        'Meeting',
        'Note',
    )
    for model_name in model_names:
        Model = apps.get_model('case_management', model_name)
        for obj in Model.objects.filter(updated_by__isnull=True, created_by__isnull=False):
            obj.updated_by = obj.created_by
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0031_merge_20220406_1010'),
    ]

    operations = [
        migrations.RunPython(add_missing_updated_by, migrations.RunPython.noop),
    ]
