# Generated by Django 3.2.4 on 2022-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0026_merge_20220407_1321'),
        ('case_management', '0032_add_missing_updated_by'),
    ]

    operations = [
    ]
