# Generated by Django 3.2.4 on 2022-04-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0027_alter_logchange_value'),
        ('case_management', '0033_merge_20220407_1340'),
    ]

    operations = [
    ]
