# Generated by Django 3.2.21 on 2023-09-22 11:39

from django.db import migrations, models
from case_management.models import Client


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0035_fix_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_names',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        )
    ]
