# Generated by Django 3.2.21 on 2023-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0036_auto_20230922_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
    ]
