# Generated by Django 3.2.21 on 2023-09-28 14:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0037_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country_of_birth',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('Call', 'Phone Call'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp/messenger'), ('Email', 'Email')], max_length=25),
        ),
    ]
