# Generated by Django 3.2.21 on 2023-10-04 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import django_lifecycle.mixins
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0042_auto_20231002_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDependent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_names', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=128)),
                ('official_identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('official_identifier_type', models.CharField(blank=True, choices=[('National', 'National Identity Number'), ('Passport', 'Passport Number'), ('RefugeePassport', 'Refugee Passport ID Number'), ('Section22AsylymSeekerVisa', 'Section 22 Asylym Seeker Visa ID Number'), ('Section24RefugeePermit', 'Section 24 Refugee Permit File Number')], max_length=25, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('alternative_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternative_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('Call', 'Phone Call'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp/messenger'), ('Email', 'Email')], max_length=25, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('PreferNotToSay', 'Prefer Not To Say')], max_length=20, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('country_of_birth', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_dependents', to='case_management.client')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_home_language', to='case_management.language')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('official_identifier', 'official_identifier_type')},
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
