# Generated by Django 3.2.21 on 2023-10-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0044_clientdependent_relationship_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission_group',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Reporting', 'Reporting'), ('AdviceOfficeAdmin', 'Office Admin'), ('CaseWorker', 'Case Worker')], max_length=20, null=True),
        ),
    ]
