# Generated by Django 3.2.23 on 2023-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0046_sitenotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdependent',
            name='relationship_to_client',
            field=models.CharField(blank=True, choices=[('Aunt', 'Aunt'), ('Brother', 'Brother'), ('Child', 'Child'), ('Cousin', 'Cousin'), ('Daughter', 'Daughter'), ('Daughter In-Law', 'Daughter In Law'), ('Father', 'Father'), ('Father In-Law', 'Father In Law'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Grandparent', 'Grandparent'), ('Great-Grandfather', 'Great Grandfather'), ('Great-Grandmother', 'Great Grandmother'), ('Great-Grandparent', 'Great Grandparent'), ('Guardian', 'Guardian'), ('In-Law', 'In Law'), ('Mother', 'Mother'), ('Mother In-Law', 'Mother In Law'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Other', 'Other'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Sister', 'Sister'), ('Son', 'Son'), ('Son In-Law', 'Son In Law'), ('Spouse', 'Spouse'), ('Uncle', 'Uncle')], default='Other', max_length=20, null=True),
        ),
    ]
