# Generated by Django 3.2.23 on 2024-01-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0048_alter_clientdependent_relationship_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of site-wide variable', max_length=200)),
                ('value', models.JSONField(blank=True, help_text='Value of site-wide variable that scripts can reference - must be valid JSON', null=True)),
            ],
        ),
    ]
