# Generated by Django 3.2.23 on 2024-01-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0049_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(help_text='Name of site-wide variable', max_length=200, unique=True),
        ),
    ]
