# Generated by Django 3.2.23 on 2024-01-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0047_clientfile'),
        ('case_management', '0051_alter_legalcase_state'),
    ]

    operations = [
    ]
